### ISSUE TITLE
Some slight suggestions

### ISSUE THREAD

**Issue by Aliencat314159** [HyperSourceGithub/hyperair#19]
Not really issues, just cool features that maybe you could add. 
1. Buildings, airports, cities, etc. 
2. People that can board the plane, luggage, other general airport stuff. 
3. Something like missions for the players: Fly from point A to point B in 10 minutes. 
4. Explosions when you crash. 
5. When you die, have stats, such as highest altitude, missions completed, time spent in the air, etc. 
6. When you crash into a bird, make small bird gut explosions. 
7. Airlines you can fly for (Getting hired, fired, stuff like that)
Anyways you should add these things.

**Comment by HyperSourceGithub** [comment]
Renamed the thing

**Comment by HyperSourceGithub** [comment]
Closing it so that it can be made to separate issues.
